"""Transactions

Revision ID: 4b205786aeb5
Revises: e46f8092a5e9
Create Date: 2025-03-01 17:38:03.683847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4b205786aeb5'
down_revision: Union[str, None] = 'e46f8092a5e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_expenses_id', table_name='expenses')
    op.drop_table('expenses')
    op.drop_index('ix_incomes_id', table_name='incomes')
    op.drop_table('incomes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incomes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('source', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('bank_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], name='incomes_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='incomes_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_incomes_id', 'incomes', ['id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('category', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('bank_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_cash', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], name='expenses_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='expenses_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_expenses_id', 'expenses', ['id'], unique=False)
    # ### end Alembic commands ###
