"""Transaction Date added

Revision ID: 7ba076daff7c
Revises: 3e0fcafd3e4d
Create Date: 2025-03-02 17:45:56.071589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba076daff7c'
down_revision: Union[str, None] = '3e0fcafd3e4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banks', sa.Column('is_credit_allow', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('transaction_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'transaction_date')
    op.drop_column('banks', 'is_credit_allow')
    # ### end Alembic commands ###
