"""Fix Bank dependency

Revision ID: 8dbcf27aa90e
Revises: b8b8ca6ea76c
Create Date: 2025-03-01 12:13:50.655767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dbcf27aa90e'
down_revision: Union[str, None] = 'b8b8ca6ea76c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
