"""Fix Bank dependency

Revision ID: b7d4a97fbcc2
Revises: 8dbcf27aa90e
Create Date: 2025-03-01 12:15:09.447149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7d4a97fbcc2'
down_revision: Union[str, None] = '8dbcf27aa90e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
