"""Fix Bank dependency

Revision ID: cddfb66dfcf0
Revises: b7d4a97fbcc2
Create Date: 2025-03-01 12:15:43.786779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cddfb66dfcf0'
down_revision: Union[str, None] = 'b7d4a97fbcc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
