"""Fix Bank dependency

Revision ID: e46f8092a5e9
Revises: cddfb66dfcf0
Create Date: 2025-03-01 12:20:40.043213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e46f8092a5e9'
down_revision: Union[str, None] = 'cddfb66dfcf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
